<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // resolve()方法将现有对象转换成Promise对象，该实例的状态为 fulfilled 成功
        let p1 = Promise.resolve('foo');
        //等价于let p = new Promise(resolve=>resolve('foo'));
        p1.then((val) => {
            console.log(val);  //'foo'
        })

        // reject()方法和resolve()方法一样返回一个新的Promise实例
        let p2 = Promise.reject(new Error('出错了'));
        //等价于 let p2 = new Promise((resolve,reject)=>reject(new Error('出错了)));
        p2.catch(err => {
            console.log(err);
        })

        // all()方法返回一个新的 Promise 对象，该对象在所有给定的 Promise 都已经完成或被拒绝后才会完成，结果是一个数组，包含了所有 Promise 的结果值。
        let pro1 = new Promise((resolve, reject) => { });
        let pro2 = new Promise((resolve, reject) => { });
        let pro3 = new Promise((resolve, reject) => { });
        let pAll = Promise.all([pro1, pro2, pro3]);
        pAll.then(val => {
            // 三个都成功 才成功
        }).cath(err => {
            // 如果一个失败 则失败
        })

        // race()方法返回一个新的 Promise 对象，该对象在给定的任意一个 Promise 完成或被拒绝后就会结束，并以该 Promise 的结果或原因作为返回的 Promise 结果或拒因。
        // 请求图片资源
        function requestImg(imgSrc) {
            return new Promise((resolve, reject) => {
                let img = new Image();
                img.onload = function () {
                    resolve(img)
                }
                img.src = imgSrc
            })
        }
        //延时函数，用于给请求计时
        function timeOut() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    reject(new Error('图片请求超时'))
                }, 3000)
            })
        }
        Promise.race([requestImg('../html_css/1day/img/头像.jpg'), timeOut()]).then(val => {
            // console.log(val);
            document.body.append(val)
        }).catch(err => {
            console.log(err);
        })
    </script>
</body>

</html>